services:
  - type: web
    name: errtrack
    runtime: python
    buildCommand: ls && pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    plan: free
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: errtrack-db
          property: connectionString
      - key: ALLOWED_ORIGINS
        value: https://errtrack.onrender.com
      - key: RENDER
        value: "true"

databases:
  - name: errtrack-db
    plan: free
    databaseName: errtrack
    user: errtrack
